### ISSUE TITLE
Request from a Human(Not A Robot)

### ISSUE THREAD

**Issue by Guru322** [PikaBotz/Anya_v2-MD#101]
After 13 ad clicks ,  16 Redirects(5  times P*rn site, 2 times zivame )  trying to prove i am not a Robot i got This 

![image](https://github.com/PikaBotz/Anya_v2-MD/assets/106463398/f8ced086-2c8c-4ca7-8b0b-37b5ed9f6e38)

Both the qrs

**Comment by Teamolduser** [comment]
Update the bot script we updated the link but by the why are you visit that site

**Comment by Guru322** [comment]
Oo uper me tha link, isiliye
Sorry

**Comment by Teamolduser** [comment]
> Oo uper me tha link, isiliye Sorry

Kidhar WhatsApp pe aao

**Comment by Guru322** [comment]
> > Oo uper me tha link, isiliye Sorry
> 
> Kidhar WhatsApp pe aao

Bhai malaria ho gya hai

**Comment by Teamolduser** [comment]
> > > Oo uper me tha link, isiliye Sorry
> > 
> > 
> > Kidhar WhatsApp pe aao
> 
> Bhai malaria ho gya hai

Kese reset Karo bro and get well soon
