### ISSUE TITLE
Implement my fork on heroku 

### ISSUE THREAD

**Issue by Marcosi8** [PikaBotz/Anya_v2-MD#139]
How can I deploy my fork on Heroku? I would like to make some changes to the command menu, but when implementing it on heroku, it is directly redirected to the original repository instead of the fork.

**Comment by PikaBotz** [comment]
👋🏻 Hey @Marcosi8,

To resolve this issue, please update the [`deployment URL`](https://github.com/Fake-404/Anya_v2-MD#:~:text=Deploy%20On%20Replit-,Deploy%20On%20Heroku,-Deploy%20on%20Heroku) with the following URL: [https://heroku.com/deploy?template=PUT_YOUR_REPO_URL_HERE](https://heroku.com/deploy?template=PUT_YOUR_REPO_URL_HERE)

Or simply just copy this link, replace & put your repo url and use this url to deploy your customised repo!

**Comment by Riders004** [comment]
> How can I deploy my fork on Heroku? I would like to make some changes to the command menu, but when implementing it on heroku, it is directly redirected to the original repository instead of the fork.

Try with button
